/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueDUtilisationRouteImport } from './routes/politique-d-utilisation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDUtilisationRoute = PolitiqueDUtilisationRouteImport.update({
  id: '/politique-d-utilisation',
  path: '/politique-d-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-d-utilisation': typeof PolitiqueDUtilisationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-d-utilisation': typeof PolitiqueDUtilisationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-d-utilisation': typeof PolitiqueDUtilisationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/conditions' | '/mentions-legales' | '/politique-d-utilisation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conditions' | '/mentions-legales' | '/politique-d-utilisation'
  id:
    | '__root__'
    | '/'
    | '/conditions'
    | '/mentions-legales'
    | '/politique-d-utilisation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsRoute: typeof ConditionsRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDUtilisationRoute: typeof PolitiqueDUtilisationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-d-utilisation': {
      id: '/politique-d-utilisation'
      path: '/politique-d-utilisation'
      fullPath: '/politique-d-utilisation'
      preLoaderRoute: typeof PolitiqueDUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsRoute: ConditionsRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDUtilisationRoute: PolitiqueDUtilisationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
